image: maven:3-eclipse-temurin-22-alpine
clean:
  script: "mvn clean -B"
compile:
  script: "mvn compile -B"
install:
  script: "mvn install -B"
  timeout: 10m
test-jdk22:
  stage: test
  image: maven:3.9.9-jdk-22
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: target/custom-jacoco-reports/jacoco.xml