image: maven:3-eclipse-temurin-22-alpine

stages:
  - clean
  - compile
  - install
  - test

clean:
  stage: clean
  script:
    - mvn clean -B

compile:
  stage: compile
  script:
    - mvn compile -B

install:
  stage: install
  script:
    - mvn install -B
  timeout: 10m

test-jdk22:
  stage: test
  image: maven:3.9.9-eclipse-temurin-22
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: target/site/jacoco/jacoco.xml 
