image: maven:3-eclipse-temurin-22-alpine

stages:
  - install
  - clean
  - compile
  - test

clean:
  stage: clean
  script:
    - mvn clean -B

compile:
  stage: compile
  script:
    - mvn compile -B

install:
  stage: install
  script:
    - mvn install -B
  timeout: 10m

test-jdk22:
  stage: test
  image: maven:3.9.9-eclipse-temurin-22
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
  coverage: '/Total.*?([0-9]{1,3})%/'   # Regular expression to capture coverage percentage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/site/custom-jacoco-reports/jacoco.xml
    paths:
      - target/site/custom-jacoco-reports  # Upload HTML report for easy browsing